jobs:
  include:
    - stage: create image
      os: linux
      dist: focal
      vm:  # existing key
        create:
          name: naruto_image
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true
      script:
        - echo "OK8"
